version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8007
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8007:8007"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=cinema
      - DB_USER=cinema_user
      - DB_PASSWORD=cinema_password
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
  media:

