# Generated by Django 4.2.16 on 2024-09-07 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_on_mins',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
