# Generated by Django 4.2.16 on 2024-09-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0002_movie_duration_on_mins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
